name: Pages Build and Deploy

on:
  workflow_run:
    workflows:
      - CI/CD Pipeline  # Replace with the name of your CI/CD workflow
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build the Site
        run: npm run build  # Adjust this command to your build process

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with your build directory
